refactor: improve tag version handling

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -6,12 +6,22 @@ install:
 before_script:
     # Run GUI apps in headless mode
     - export DISPLAY=:99.0
-    - if [[ $TRAVIS_TAG =~ ^v ]]; then
+    - if [[ ($TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+$) || ($TRAVIS_TAG =~ ^RELEASE_CANDIDATE) ]]; then
         export TEST_REPORT_SANDBOX=False;
+        export SDK_VERSION=$(echo $TRAVIS_TAG | sed 's/[^.0-9]*//g');
+        export TMP_CHANGELOG=$(bash ./extractChangeLog.sh "$SDK_VERSION" "CHANGELOG.md");
+        export CHANGELOG=$([ -z "$TMP_CHANGELOG" ] && echo "There is no change log for version $SDK_VERSION"; echo "$TMP_CHANGELOG");
+
+        if [[ (-z "$TMP_CHANGELOG") ]]; then
+            echo "THE CHANGELOG IS NOT CORRECT";
+            exit 1;
+        fi
+
       fi
     - export APPLITOOLS_BATCH_ID=`python -c "import uuid;print(str(uuid.uuid4()))"`
 script:
     - echo "TRAVIS_COMMIT=$TRAVIS_COMMIT" "BUILD_TAG=$BUILD_TAG" "TRAVIS_TAG=$TRAVIS_TAG"
+    - echo "v$SDK_VERSION $CHANGELOG"
     - echo $TEST_REPORT_SANDBOX
     - echo $APPLITOOLS_BATCH_ID
     - tox -e $TOX_ENV
@@ -29,25 +39,18 @@ jobs:
           env:
               - TOX_ENV=lint
         - stage: bumpversion
-          if: tag =~ ^RELEASE_CANDIDATE AND fork == false AND branch == develop
+          if: tag =~ ^RELEASE_CANDIDATE AND fork == false
           script:
-          - SDK_VERSION=$(echo $TRAVIS_TAG | sed 's/[^.0-9]*//g')
-          - echo $SDK_VERSION
-          - chmod +x ./extractChangeLog.sh
-          - TMP_CHANGELOG=$(./extractChangeLog.sh "$SDK_VERSION" "CHANGELOG.md")
-          - echo "$TMP_CHANGELOG"
-          - CHANGELOG=$([ -z "$TMP_CHANGELOG" ] && echo "ERROR === There is no change log for version $SDK_VERSION" || echo "$TMP_CHANGELOG")
-          - echo $CHANGELOG
-          - if [[ (-z "$TMP_CHANGELOG") && ($TRAVIS_TAG =~ ^RELEASE_CANDIDATE) ]]; then
-            sleep 5;
-            exit 1;
-            fi
-          - if [[ $TRAVIS_TAG =~ ^RELEASE_CANDIDATE ]]; then
-            pip install bump2version;
-            bumpversion --allow-dirty --new-version $SDK_VERSION patch;
-            git remote set-url origin https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG};
-            git push --tags origin HEAD:$RELEASE_BRANCH;
-            fi
+              - echo "v$SDK_VERSION $CHANGELOG"
+              - if [[ "$TMP_CHANGELOG" ]]; then
+                  pip install bump2version;
+                  bumpversion --new-version $SDK_VERSION patch;
+                  git remote set-url origin https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG};
+                  git push --tags origin HEAD:$RELEASE_BRANCH;
+                else
+                  echo "THE CHANGELOG IS NOT CORRECT";
+                  exit 1;
+                fi
 
         - stage: unit-tests
           python: 2.7
@@ -169,27 +172,22 @@ jobs:
               - TEST_PLATFORM=Linux
               - TEST_BROWSERS=chrome
         - stage: deploy
-          if: tag =~ ^v AND fork == false AND branch == develop
+          if: tag =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ AND fork == false
           python: 3.6
           script:
-              # save the email of the person who did this commit in COMMITTER_EMAIL
               - pip install -U invoke twine
+              - echo "v$SDK_VERSION $CHANGELOG"
+              - echo $TMP_CHANGELOG
+              # save the email of the person who did this commit in COMMITTER_EMAIL
               - COMMITTER_EMAIL="$(git log -1 $TRAVIS_COMMIT --pretty="%cE")"
-              - SDK_VERSION=$(echo $TRAVIS_TAG | sed 's/[^.0-9]*//g')
-              - if [[ $COMMITTER_EMAIL =~ $ALLOWED_RELEASE_COMMITERS ]]; then
+              - if [[ ("$ALLOWED_RELEASE_COMMITERS" =~ .*"$COMMITTER_EMAIL".*) && $TMP_CHANGELOG ]]; then
                   echo "DEPLOY";
-                  TMP_CHANGELOG=$(bash ./extractChangeLog.sh "$SDK_VERSION" "CHANGELOG.md");
-
-                  if [[ (-z "$TMP_CHANGELOG") && ($TRAVIS_TAG =~ ^v) ]]; then
-                  sleep 5;
-                  exit 1;
-                  fi
-
-                  CHANGELOG=$([ -z "$TMP_CHANGELOG" ] && echo "There is no change log for version $SDK_VERSION"; echo "$TMP_CHANGELOG");
-                  echo $CHANGELOG;
-
                   TEST_COVERAGE_GAP=$(cat testCoverageGap.txt);
                   bash ./sendMail.sh "$SDK" "$TRAVIS_TAG" "$CHANGELOG" "$TEST_COVERAGE_GAP";
 
                   inv dist --from-env;
+                  echo "DEPLOY SUCCESSFUL";
+                else
+                  echo "DEPLOYMENT FAILED";
+                  exit 1;
                 fi
